language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.4"
install:
  - cd /home/travis/build/power10dan/tldrResearchPaper/uploads/requirements/requirements.txt
  - pip install -r requirements.txt
script:
  - py.test