language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.4"
install:
  - pip install -r ./uploads/requirements/requirements_dev.txt
notifications:
  email: false
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres
script:
  - python manage.py migrate
  - python manage.py runserver
  - cd ./react-front-end/
  - npm install
  - npm start
  - py.test