// Constants for paper-related operations 
export const CACHED_PAPERS = "CACHED_PAPERS";
export const PAPERS_SELECTED = "PAPERS_SELECTED";
export const CACHED_PAPER_ORIGINAL = "CACHED_PAPER_ORIGINAL";
export const CACHED_PAPER_CITED = "CACHED_PAPER_CITED";
export const CACHED_PAPER_ORIGINAL_CHILDREN = "CACHED_PAPER_ORIGINAL_CHILDREN";
// Constants for app-related operations 
export const CURR_PAGE = "CURR_PAGE";
export const IS_GET_TOKEN = "IS_GET_TOKEN";
export const IS_LOGIN = "IS_LOGIN";
export const TOKEN_UPDATE = "TOKEN_UPDATE";
export const TYPE_OF_RESEARCHER = "TYPE_OF_RESEARCHER";
export const PREF_CONFERENCE = "PREFERENCE_CONFERENCE";
export const FILE_TO_UPLOAD = "FILE_TO_UPLOAD";
export const APP_ISLOADING = "APP_ISLOADING";
export const ERROR = "ERROR";
// Constants for tutorial related filters
export const CONFERENCE_FILTER = "CONFERENCE_FILTER";
export const RESEARCHER_FILTER = "RESEARCHER_FILTER";
export const SEARCHED_PAPER = "SEARCHED_PAPER";
export const RECOMMENDED_PAPER = "RECOMMENDED_PAPER";
