# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaperUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Owner', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('abstract', models.CharField(max_length=255)),
                ('DataFile', models.FileField(upload_to='', verbose_name='PDFFolder/')),
            ],
            options={
                'ordering': ('Created', 'Owner', 'DataFile', 'title', 'abstract'),
            },
        ),
    ]
