# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-02 01:54
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/documents'), upload_to=b'')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
